# Generated by Django 4.2 on 2025-04-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trade_exchange_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryOptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('UP', 'Higher'), ('DOWN', 'Lower')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('expiry_time', models.DateTimeField()),
                ('expiry_seconds', models.IntegerField()),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WON', 'Won'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
